name: Docker Build & Publish

on:
    push:
        branches:
            - master

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar mi repositorio
              uses: actions/checkout@v4

            - name: Login a Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

            - name: Crear la imagen
              run: docker build -t josaplus/music-api-411
:latest .

            - name: Publicar imagen
              run: docker push josaplus/music-api-411
:latest

    migrate-db:
        runs-on: ubuntu-latest
        needs: build-and-publish
        steps:
            - name: Ejecuta las migraciones SI ES QUE HAY!!!
              run: |
                docker container run --rm \
                -e DATABASE_HOST=${{secrets.DATABASE_HOST}} \
                -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
                -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
                -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
                -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
                juanfr97/music-api-411:latest migrate --yes